# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMS_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BMS_Dashboard(object):
    def setupUi(self, BMS_Dashboard):
        BMS_Dashboard.setObjectName("BMS_Dashboard")
        BMS_Dashboard.resize(432, 574)
        self.BMS_Diagnostics_Dashboard_Title = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.BMS_Diagnostics_Dashboard_Title.setGeometry(QtCore.QRect(0, 0, 431, 31))
        self.BMS_Diagnostics_Dashboard_Title.setAutoFillBackground(False)
        self.BMS_Diagnostics_Dashboard_Title.setObjectName("BMS_Diagnostics_Dashboard_Title")
        self.CellVoltageBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.CellVoltageBlockTitle.setGeometry(QtCore.QRect(10, 40, 131, 31))
        self.CellVoltageBlockTitle.setObjectName("CellVoltageBlockTitle")
        self.label_5 = QtWidgets.QLabel(BMS_Dashboard)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 111, 16))
        self.label_5.setObjectName("label_5")
        self.VolatgeBackground = QtWidgets.QMdiArea(BMS_Dashboard)
        self.VolatgeBackground.setGeometry(QtCore.QRect(10, 70, 131, 81))
        self.VolatgeBackground.setObjectName("VolatgeBackground")
        self.label_6 = QtWidgets.QLabel(BMS_Dashboard)
        self.label_6.setGeometry(QtCore.QRect(160, 70, 111, 16))
        self.label_6.setObjectName("label_6")
        self.CellCurrentBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.CellCurrentBlockTitle.setGeometry(QtCore.QRect(150, 40, 131, 31))
        self.CellCurrentBlockTitle.setObjectName("CellCurrentBlockTitle")
        self.CurrentBackground = QtWidgets.QMdiArea(BMS_Dashboard)
        self.CurrentBackground.setGeometry(QtCore.QRect(150, 70, 131, 81))
        self.CurrentBackground.setObjectName("CurrentBackground")
        self.label_7 = QtWidgets.QLabel(BMS_Dashboard)
        self.label_7.setGeometry(QtCore.QRect(300, 70, 111, 16))
        self.label_7.setObjectName("label_7")
        self.CellTempBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.CellTempBlockTitle.setGeometry(QtCore.QRect(290, 40, 131, 31))
        self.CellTempBlockTitle.setObjectName("CellTempBlockTitle")
        self.TempBackground = QtWidgets.QMdiArea(BMS_Dashboard)
        self.TempBackground.setGeometry(QtCore.QRect(290, 70, 131, 81))
        self.TempBackground.setObjectName("TempBackground")
        self.CriticalFaultsBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.CriticalFaultsBlockTitle.setGeometry(QtCore.QRect(10, 160, 411, 31))
        self.CriticalFaultsBlockTitle.setObjectName("CriticalFaultsBlockTitle")
        self.CriticalFaultsBlockBackground = QtWidgets.QMdiArea(BMS_Dashboard)
        self.CriticalFaultsBlockBackground.setGeometry(QtCore.QRect(10, 190, 411, 81))
        self.CriticalFaultsBlockBackground.setObjectName("CriticalFaultsBlockBackground")
        self.label_8 = QtWidgets.QLabel(BMS_Dashboard)
        self.label_8.setGeometry(QtCore.QRect(20, 190, 111, 16))
        self.label_8.setObjectName("label_8")
        self.CriticalFaultsResultBox = QtWidgets.QTextEdit(BMS_Dashboard)
        self.CriticalFaultsResultBox.setEnabled(False)
        self.CriticalFaultsResultBox.setGeometry(QtCore.QRect(20, 210, 391, 51))
        self.CriticalFaultsResultBox.setObjectName("CriticalFaultsResultBox")
        self.BeaconResultBoxMAIN = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.BeaconResultBoxMAIN.setGeometry(QtCore.QRect(20, 90, 111, 51))
        self.BeaconResultBoxMAIN.setObjectName("BeaconResultBoxMAIN")
        self.BeaconResultBoxMAIN_2 = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.BeaconResultBoxMAIN_2.setGeometry(QtCore.QRect(160, 90, 111, 51))
        self.BeaconResultBoxMAIN_2.setObjectName("BeaconResultBoxMAIN_2")
        self.BeaconResultBoxMAIN_3 = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.BeaconResultBoxMAIN_3.setGeometry(QtCore.QRect(300, 90, 111, 51))
        self.BeaconResultBoxMAIN_3.setObjectName("BeaconResultBoxMAIN_3")
        self.label_9 = QtWidgets.QLabel(BMS_Dashboard)
        self.label_9.setGeometry(QtCore.QRect(20, 310, 111, 16))
        self.label_9.setObjectName("label_9")
        self.BeaconResultBoxMAIN_4 = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.BeaconResultBoxMAIN_4.setGeometry(QtCore.QRect(20, 330, 111, 51))
        self.BeaconResultBoxMAIN_4.setObjectName("BeaconResultBoxMAIN_4")
        self.SignalMonitoringBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.SignalMonitoringBlockTitle.setGeometry(QtCore.QRect(10, 280, 211, 31))
        self.SignalMonitoringBlockTitle.setObjectName("SignalMonitoringBlockTitle")
        self.ForceAreaMAIN_4 = QtWidgets.QMdiArea(BMS_Dashboard)
        self.ForceAreaMAIN_4.setGeometry(QtCore.QRect(10, 310, 211, 251))
        self.ForceAreaMAIN_4.setObjectName("ForceAreaMAIN_4")
        self.StateMonitoringBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.StateMonitoringBlockTitle.setGeometry(QtCore.QRect(230, 280, 191, 31))
        self.StateMonitoringBlockTitle.setObjectName("StateMonitoringBlockTitle")
        self.StateOfChargeResult = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.StateOfChargeResult.setGeometry(QtCore.QRect(50, 350, 141, 41))
        self.StateOfChargeResult.setObjectName("StateOfChargeResult")
        self.StateOfChargeBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.StateOfChargeBlockTitle.setGeometry(QtCore.QRect(50, 320, 141, 31))
        self.StateOfChargeBlockTitle.setObjectName("StateOfChargeBlockTitle")
        self.StateOfHealthBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.StateOfHealthBlockTitle.setGeometry(QtCore.QRect(50, 400, 141, 31))
        self.StateOfHealthBlockTitle.setObjectName("StateOfHealthBlockTitle")
        self.StateOfHealthResult = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.StateOfHealthResult.setGeometry(QtCore.QRect(50, 430, 141, 41))
        self.StateOfHealthResult.setObjectName("StateOfHealthResult")
        self.StateOfPowerBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.StateOfPowerBlockTitle.setGeometry(QtCore.QRect(50, 480, 141, 31))
        self.StateOfPowerBlockTitle.setObjectName("StateOfPowerBlockTitle")
        self.StateOfPowerResult = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.StateOfPowerResult.setGeometry(QtCore.QRect(50, 510, 141, 41))
        self.StateOfPowerResult.setObjectName("StateOfPowerResult")
        self.ForceAreaMAIN_5 = QtWidgets.QMdiArea(BMS_Dashboard)
        self.ForceAreaMAIN_5.setGeometry(QtCore.QRect(230, 310, 191, 251))
        self.ForceAreaMAIN_5.setObjectName("ForceAreaMAIN_5")
        self.ControlsBoxTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.ControlsBoxTitle.setGeometry(QtCore.QRect(240, 320, 171, 31))
        self.ControlsBoxTitle.setObjectName("ControlsBoxTitle")
        self.ContactorStateBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.ContactorStateBlockTitle.setGeometry(QtCore.QRect(240, 360, 101, 31))
        self.ContactorStateBlockTitle.setObjectName("ContactorStateBlockTitle")
        self.ContactorStateBlockStatusOutput = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.ContactorStateBlockStatusOutput.setGeometry(QtCore.QRect(350, 360, 61, 31))
        self.ContactorStateBlockStatusOutput.setObjectName("ContactorStateBlockStatusOutput")
        self.XX_1_StateBlockStatusOutput = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.XX_1_StateBlockStatusOutput.setGeometry(QtCore.QRect(350, 400, 61, 31))
        self.XX_1_StateBlockStatusOutput.setObjectName("XX_1_StateBlockStatusOutput")
        self.XX_1_StateBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.XX_1_StateBlockTitle.setGeometry(QtCore.QRect(240, 400, 101, 31))
        self.XX_1_StateBlockTitle.setObjectName("XX_1_StateBlockTitle")
        self.XX_2_StateBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.XX_2_StateBlockTitle.setGeometry(QtCore.QRect(240, 440, 101, 31))
        self.XX_2_StateBlockTitle.setObjectName("XX_2_StateBlockTitle")
        self.XX_2_StateBlockStatusOutput = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.XX_2_StateBlockStatusOutput.setGeometry(QtCore.QRect(350, 440, 61, 31))
        self.XX_2_StateBlockStatusOutput.setObjectName("XX_2_StateBlockStatusOutput")
        self.XX_3_StateBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.XX_3_StateBlockTitle.setGeometry(QtCore.QRect(240, 480, 101, 31))
        self.XX_3_StateBlockTitle.setObjectName("XX_3_StateBlockTitle")
        self.XX_3_StateBlockStatusOutput = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.XX_3_StateBlockStatusOutput.setGeometry(QtCore.QRect(350, 480, 61, 31))
        self.XX_3_StateBlockStatusOutput.setObjectName("XX_3_StateBlockStatusOutput")
        self.XX_4_StateBlockTitle = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.XX_4_StateBlockTitle.setGeometry(QtCore.QRect(240, 520, 101, 31))
        self.XX_4_StateBlockTitle.setObjectName("XX_4_StateBlockTitle")
        self.XX_4_StateBlockStatusOutput = QtWidgets.QTextBrowser(BMS_Dashboard)
        self.XX_4_StateBlockStatusOutput.setGeometry(QtCore.QRect(350, 520, 61, 31))
        self.XX_4_StateBlockStatusOutput.setObjectName("XX_4_StateBlockStatusOutput")
        self.BMS_Diagnostics_Dashboard_Title.raise_()
        self.VolatgeBackground.raise_()
        self.CellVoltageBlockTitle.raise_()
        self.label_5.raise_()
        self.CurrentBackground.raise_()
        self.label_6.raise_()
        self.CellCurrentBlockTitle.raise_()
        self.TempBackground.raise_()
        self.label_7.raise_()
        self.CellTempBlockTitle.raise_()
        self.CriticalFaultsBlockBackground.raise_()
        self.label_8.raise_()
        self.CriticalFaultsResultBox.raise_()
        self.CriticalFaultsBlockTitle.raise_()
        self.BeaconResultBoxMAIN.raise_()
        self.BeaconResultBoxMAIN_2.raise_()
        self.BeaconResultBoxMAIN_3.raise_()
        self.label_9.raise_()
        self.BeaconResultBoxMAIN_4.raise_()
        self.ForceAreaMAIN_4.raise_()
        self.StateOfChargeResult.raise_()
        self.StateOfChargeBlockTitle.raise_()
        self.StateOfHealthBlockTitle.raise_()
        self.StateOfHealthResult.raise_()
        self.StateOfPowerBlockTitle.raise_()
        self.StateOfPowerResult.raise_()
        self.ForceAreaMAIN_5.raise_()
        self.ControlsBoxTitle.raise_()
        self.ContactorStateBlockTitle.raise_()
        self.ContactorStateBlockStatusOutput.raise_()
        self.StateMonitoringBlockTitle.raise_()
        self.SignalMonitoringBlockTitle.raise_()
        self.XX_1_StateBlockStatusOutput.raise_()
        self.XX_1_StateBlockTitle.raise_()
        self.XX_2_StateBlockTitle.raise_()
        self.XX_2_StateBlockStatusOutput.raise_()
        self.XX_3_StateBlockTitle.raise_()
        self.XX_3_StateBlockStatusOutput.raise_()
        self.XX_4_StateBlockTitle.raise_()
        self.XX_4_StateBlockStatusOutput.raise_()

        self.retranslateUi(BMS_Dashboard)
        QtCore.QMetaObject.connectSlotsByName(BMS_Dashboard)

    def retranslateUi(self, BMS_Dashboard):
        _translate = QtCore.QCoreApplication.translate
        BMS_Dashboard.setWindowTitle(_translate("BMS_Dashboard", "Dialog"))
        self.BMS_Diagnostics_Dashboard_Title.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🔋 </span><span style=\" font-size:11pt; font-weight:600;\">BMS Diagnostics Dashboard </span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🔋</span></p></body></html>"))
        self.CellVoltageBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt;\">⚡️ </span><span style=\" font-size:9pt; color:#00007f;\">Volatge (V) </span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt;\">⚡️</span></p></body></html>"))
        self.label_5.setText(_translate("BMS_Dashboard", "Measured Cell Voltage"))
        self.label_6.setText(_translate("BMS_Dashboard", "Measured Cell Current"))
        self.CellCurrentBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt;\">🔌 </span><span style=\" font-size:9pt; color:#00007f;\">Current (A) </span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt;\">🔌</span></p></body></html>"))
        self.label_7.setText(_translate("BMS_Dashboard", "Measured Cell Temp"))
        self.CellTempBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt;\">🌡️ </span><span style=\" font-size:9pt; color:#00007f;\">Temperature (F) </span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt;\">🌡️</span></p></body></html>"))
        self.CriticalFaultsBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt; font-weight:600;\">🚨 </span><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">Critical Faults/Flags</span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt; font-weight:600;\">🚨</span></p></body></html>"))
        self.label_8.setText(_translate("BMS_Dashboard", "Fault Message:"))
        self.CriticalFaultsResultBox.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.BeaconResultBoxMAIN.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.BeaconResultBoxMAIN_2.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.BeaconResultBoxMAIN_3.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label_9.setText(_translate("BMS_Dashboard", "Measured Cell Voltage"))
        self.BeaconResultBoxMAIN_4.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.SignalMonitoringBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:10pt;\">Signal Monitoring</span></p></body></html>"))
        self.StateMonitoringBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:10pt;\">State Monitoring</span></p></body></html>"))
        self.StateOfChargeResult.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.StateOfChargeBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt;\">State of Charge</span></p></body></html>"))
        self.StateOfHealthBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt;\">State of Health</span></p></body></html>"))
        self.StateOfHealthResult.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.StateOfPowerBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt;\">State of Power</span></p></body></html>"))
        self.StateOfPowerResult.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.ControlsBoxTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#0000ff;\">Controls🔧</span></p></body></html>"))
        self.ContactorStateBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:8pt;\">Contactor State</span></p></body></html>"))
        self.ContactorStateBlockStatusOutput.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.XX_1_StateBlockStatusOutput.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.XX_1_StateBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:8pt;\">XX State</span></p></body></html>"))
        self.XX_2_StateBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:8pt;\">XX State</span></p></body></html>"))
        self.XX_2_StateBlockStatusOutput.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.XX_3_StateBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:8pt;\">XX State</span></p></body></html>"))
        self.XX_3_StateBlockStatusOutput.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.XX_4_StateBlockTitle.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:8pt;\">XX State</span></p></body></html>"))
        self.XX_4_StateBlockStatusOutput.setHtml(_translate("BMS_Dashboard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BMS_Dashboard = QtWidgets.QDialog()
    ui = Ui_BMS_Dashboard()
    ui.setupUi(BMS_Dashboard)
    BMS_Dashboard.show()
    sys.exit(app.exec_())
